# ARI Master Brain - Emotionally Adaptive Humanoid AI
# Copyright (c) 2020–2025 Tyrell Murray (ATVOM LLC - Vertex Fusion Robotics)
#
# All rights reserved. This software is the original work of the author.
# Unauthorized reproduction, modification, or distribution is prohibited.
#
# For licensing inquiries, contact: tyrellmurray28@gmail.com
import json

expressions = {
    "neutral": {
        "left_eyebrow_outer": 90,
        "left_eyebrow_inner": 90,
        "right_eyebrow_inner": 90,
        "right_eyebrow_outer": 90,
        "eyelid_left": 90,
        "eyelid_right": 90,
        "eye_vertical": 90,
        "eye_horizontal": 90,
        "left_cheek_upper": 90,
        "left_cheek_lower": 90,
        "right_cheek_upper": 90,
        "right_cheek_lower": 90,
        "top_cheek_left": 90,
        "top_cheek_right": 90,
        "top_lip_left": 90,
        "top_lip_center": 90,
        "top_lip_right": 90,
        "bottom_lip_left": 90,
        "bottom_lip_center": 90,
        "bottom_lip_right": 90,
        "mouth": 90
    },
    "happy": {
        "left_eyebrow_inner": 100,
        "right_eyebrow_inner": 100,
        "left_eyebrow_outer": 95,
        "right_eyebrow_outer": 95,
        "eyelid_left": 85,
        "eyelid_right": 85,
        "eye_vertical": 90,
        "eye_horizontal": 90,
        "left_cheek_upper": 120,
        "right_cheek_upper": 120,
        "top_lip_left": 110,
        "top_lip_center": 110,
        "top_lip_right": 110,
        "bottom_lip_left": 130,
        "bottom_lip_center": 130,
        "bottom_lip_right": 130,
        "mouth": 120
    },
    "sad": {
        "left_eyebrow_inner": 60,
        "right_eyebrow_inner": 60,
        "left_eyebrow_outer": 80,
        "right_eyebrow_outer": 80,
        "eyelid_left": 100,
        "eyelid_right": 100,
        "eye_vertical": 92,
        "eye_horizontal": 90,
        "left_cheek_lower": 70,
        "right_cheek_lower": 70,
        "top_lip_left": 75,
        "top_lip_center": 80,
        "top_lip_right": 75,
        "bottom_lip_left": 70,
        "bottom_lip_center": 70,
        "bottom_lip_right": 70,
        "mouth": 70
    },
    "surprised": {
        "left_eyebrow_inner": 120,
        "right_eyebrow_inner": 120,
        "left_eyebrow_outer": 115,
        "right_eyebrow_outer": 115,
        "eyelid_left": 60,
        "eyelid_right": 60,
        "eye_vertical": 95,
        "eye_horizontal": 90,
        "left_cheek_upper": 90,
        "right_cheek_upper": 90,
        "top_lip_left": 100,
        "top_lip_center": 120,
        "top_lip_right": 100,
        "bottom_lip_left": 120,
        "bottom_lip_center": 140,
        "bottom_lip_right": 120,
        "mouth": 150
    },
    "angry": {
        "left_eyebrow_inner": 60,
        "right_eyebrow_inner": 60,
        "left_eyebrow_outer": 110,
        "right_eyebrow_outer": 110,
        "eyelid_left": 95,
        "eyelid_right": 95,
        "eye_vertical": 88,
        "eye_horizontal": 90,
        "left_cheek_upper": 100,
        "right_cheek_upper": 100,
        "top_lip_left": 80,
        "top_lip_center": 85,
        "top_lip_right": 80,
        "bottom_lip_left": 80,
        "bottom_lip_center": 80,
        "bottom_lip_right": 80,
        "mouth": 60
    },
    "fear": {
        "left_eyebrow_inner": 120,
        "right_eyebrow_inner": 120,
        "left_eyebrow_outer": 80,
        "right_eyebrow_outer": 80,
        "eyelid_left": 70,
        "eyelid_right": 70,
        "eye_vertical": 95,
        "eye_horizontal": 90,
        "left_cheek_upper": 80,
        "right_cheek_upper": 80,
        "top_lip_left": 80,
        "top_lip_center": 90,
        "top_lip_right": 80,
        "bottom_lip_left": 120,
        "bottom_lip_center": 130,
        "bottom_lip_right": 120,
        "mouth": 140
    },
    "disgust": {
        "left_eyebrow_inner": 70,
        "right_eyebrow_inner": 70,
        "left_eyebrow_outer": 60,
        "right_eyebrow_outer": 60,
        "eyelid_left": 100,
        "eyelid_right": 100,
        "eye_vertical": 88,
        "eye_horizontal": 90,
        "left_cheek_upper": 110,
        "right_cheek_upper": 110,
        "top_lip_left": 70,
        "top_lip_center": 75,
        "top_lip_right": 70,
        "bottom_lip_left": 60,
        "bottom_lip_center": 60,
        "bottom_lip_right": 60,
        "mouth": 60
    },
    "contempt": {
        "left_eyebrow_inner": 90,
        "right_eyebrow_inner": 80,
        "left_eyebrow_outer": 90,
        "right_eyebrow_outer": 80,
        "eyelid_left": 90,
        "eyelid_right": 90,
        "eye_vertical": 90,
        "eye_horizontal": 90,
        "left_cheek_upper": 100,
        "right_cheek_upper": 80,
        "top_lip_left": 110,
        "top_lip_center": 90,
        "top_lip_right": 80,
        "bottom_lip_left": 110,
        "bottom_lip_center": 90,
        "bottom_lip_right": 80,
        "mouth": 100
    },
    "sleepy": {
        "left_eyebrow_inner": 80,
        "right_eyebrow_inner": 80,
        "left_eyebrow_outer": 80,
        "right_eyebrow_outer": 80,
        "eyelid_left": 120,
        "eyelid_right": 120,
        "eye_vertical": 90,
        "eye_horizontal": 90,
        "left_cheek_upper": 90,
        "right_cheek_upper": 90,
        "top_lip_left": 85,
        "top_lip_center": 85,
        "top_lip_right": 85,
        "bottom_lip_left": 85,
        "bottom_lip_center": 85,
        "bottom_lip_right": 85,
        "mouth": 80
    },
    "thinking": {
        "left_eyebrow_inner": 85,
        "right_eyebrow_inner": 85,
        "left_eyebrow_outer": 85,
        "right_eyebrow_outer": 85,
        "eyelid_left": 95,
        "eyelid_right": 95,
        "eye_vertical": 88,
        "eye_horizontal": 85,
        "left_cheek_upper": 90,
        "right_cheek_upper": 90,
        "top_lip_left": 85,
        "top_lip_center": 85,
        "top_lip_right": 85,
        "bottom_lip_left": 85,
        "bottom_lip_center": 85,
        "bottom_lip_right": 85,
        "mouth": 85
    },
    "confused": {
        "left_eyebrow_inner": 75,
        "right_eyebrow_inner": 105,
        "left_eyebrow_outer": 105,
        "right_eyebrow_outer": 75,
        "eyelid_left": 90,
        "eyelid_right": 90,
        "eye_vertical": 90,
        "eye_horizontal": 88,
        "left_cheek_upper": 85,
        "right_cheek_upper": 95,
        "top_lip_left": 85,
        "top_lip_center": 90,
        "top_lip_right": 95,
        "bottom_lip_left": 85,
        "bottom_lip_center": 90,
        "bottom_lip_right": 95,
        "mouth": 85
    },
    "concerned": {
        "left_eyebrow_inner": 70,
        "right_eyebrow_inner": 70,
        "left_eyebrow_outer": 85,
        "right_eyebrow_outer": 85,
        "eyelid_left": 95,
        "eyelid_right": 95,
        "eye_vertical": 92,
        "eye_horizontal": 90,
        "left_cheek_upper": 85,
        "right_cheek_upper": 85,
        "top_lip_left": 80,
        "top_lip_center": 80,
        "top_lip_right": 80,
        "bottom_lip_left": 75,
        "bottom_lip_center": 75,
        "bottom_lip_right": 75,
        "mouth": 75
    },
    "wink_left": {
        "left_eyebrow_inner": 100,
        "right_eyebrow_inner": 90,
        "left_eyebrow_outer": 100,
        "right_eyebrow_outer": 90,
        "eyelid_left": 130,
        "eyelid_right": 85,
        "eye_vertical": 90,
        "eye_horizontal": 90,
        "left_cheek_upper": 110,
        "right_cheek_upper": 90,
        "top_lip_left": 110,
        "top_lip_center": 100,
        "top_lip_right": 90,
        "bottom_lip_left": 110,
        "bottom_lip_center": 100,
        "bottom_lip_right": 90,
        "mouth": 110
    },
    "wink_right": {
        "left_eyebrow_inner": 90,
        "right_eyebrow_inner": 100,
        "left_eyebrow_outer": 90,
        "right_eyebrow_outer": 100,
        "eyelid_left": 85,
        "eyelid_right": 130,
        "eye_vertical": 90,
        "eye_horizontal": 90,
        "left_cheek_upper": 90,
        "right_cheek_upper": 110,
        "top_lip_left": 90,
        "top_lip_center": 100,
        "top_lip_right": 110,
        "bottom_lip_left": 90,
        "bottom_lip_center": 100,
        "bottom_lip_right": 110,
        "mouth": 110
    }
}

def send_expression(expression_name):
    if expression_name not in expressions:
        print(f"Unknown expression: {expression_name}")
        return
    msg = json.dumps(expressions[expression_name])
    print(f"Would send to Arduino: {msg}")

if __name__ == "__main__":
    # Test all expressions
    for expr in expressions:
        send_expression(expr)
